// pell series:-
// 0 1 2 5 12 29 70
// every number is generated by adding twice of previous number+ the no before that.
import java.util.*;
public class pell_series {
    public static void main(String[] args) {
        Scanner sc= new Scanner(System.in);
        int n= sc.nextInt();
        int a1=0, a2=1;
        System.out.print(0+" "+ 1+ " ");
        for(int i=1; i<=n-2; i++){
           int a3= (2*a2) +a1;
           System.out.print(a3+" ");
           a1=a2;
           a2=a3;
        }
    }
}
